version: '2'
services:
    scorekeeper-app:
        image: scorekeeper
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://scorekeeper-mysql:3306/scorekeeper?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    scorekeeper-mysql:
        extends:
            file: mysql.yml
            service: scorekeeper-mysql
